#!/usr/bin/env bash

set -e

ghc src/Client.hs -o src/Client
export RTMHOST="wss://cerberus-xxxx.lb.slack-msgs.com"
export RTMPATH=$(
    curl "https://slack.com/api/rtm.connect?token=$SLACK_BOT_TOKEN" \
        | jq -r '.url' \
        | sed 's/wss.*com//g'
)
./src/Client
