#!/usr/bin/env bash

set -e

extract() {
    a='s/wss:\/\/\(.*\.com\)\(.*\)/\'
    b='/g'
    echo $1 | sed $a$2$b
}

ghc src/Chat.hs src/Client.hs -o src/Client
response=$(
    curl "https://slack.com/api/rtm.connect?token=$SLACK_BOT_TOKEN" \
        | jq -r '.url'
)
export RTMHOST=$(extract $response "1")
export RTMPATH=$(extract $response "2")
./src/Client
