#!/usr/bin/env bash

set -e

if [[ $1 = "lint" ]]; then
    find . -name "*.hs" -exec bash -c 'lint "$0"' {} \;
fi
ghc \
    src/Types.hs src/Chat.hs src/Bridge.hs src/test/Test.hs \
    -o bin/Test
./bin/Test
